# @format

name: pipleLine
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pipleLine:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pipleLine
        run: npm ci && npm run build
